### ISSUE TITLE
Code formatting - from discussion in PR

### ISSUE THREAD

**Issue by poggenpower** [fhemberger/mqtt_exporter#24]
Moved the question about the formatting here, to separate it from the PR.

Yes I am usinga tool for formatting. It is `autopep8` https://pypi.org/project/autopep8/ which is the default formatter in VSCode and I run it with the default config. It is following the the Python code styling guidelines. 
My experience is, that it works pretty well. But I am open to do it different, if is follows roughly the python code styling guidelines and limters will also not complain about the formatting. 
I agree we should commit to one standard to aviod "random" code changes depending on the developer.

Code linting could be another topic. Here I typically fix critical findings, but some lower I ignore.

**Comment by fhemberger** [comment]
Thanks, added set `autopep8` as formatter in my local `.vscode` config, which resulted in a few minor [whitespace changes](https://github.com/fhemberger/mqtt_exporter/commit/ce138bba7ba7e347ccc18740f6290c96d96080c5). I added its usage to the README as well.

Personally, I've been using [`black`](https://github.com/psf/black) for projects lately - it's opinionated, not configurable and just ends coding style discussions similar to `go fmt`. 😉 

But I really don't care if we use one over the other, as long as there is agreement over *some* sort of code formatting.

**Comment by poggenpower** [comment]
Heared about black but never tested it. I am not opinionated about opinionated tools ;-).  I am open to switch if you think it is worth to use.
