### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by poggenpower** [fhemberger/mqtt_exporter#25]
How is the release workflow working. 
The "build" action runs if a new tag is added and pushes to dockerhub and ghcr, but I'm missing the part where the version in the mqtt_exporter.py get changed. Or is it a manual step?

**Comment by fhemberger** [comment]
Yes, at the moment the version number in the Python file is increased manually. So far I've tagged that commit with the new version, but I'm open to improve that process.

**Comment by poggenpower** [comment]
I am thinking of an approace I saw in other projects. 

Releases and version bumps get triggered by a keyword in the commit message to the master branch.
e.g. 
fix: will increase the last tuple 
feat: will increase the middle tuple / minor release
BREAKING_CHANGE: will increase the first tuple / major release.
No keyword means no release/version bump
If we want to get fancy keywords like chore, docs, ...  can trigger other things. 
Similar to https://www.conventionalcommits.org/en/v1.0.0/#summary

Implementation could be made by integrating https://github.com/c4urself/bump2version into the build action. 
It will write the versions into the required files. 

As the version bump will be an additionl commit I would suggest to move the version out of `mqtt_expoert.py` and write it into a seperate file `version.py`. Then `mqtt_exporter.py`  won't get additional changes and git log/blame/overview stays clear. If mqtt_exporter.py needs to be aware of its version `import version` should bring it in. 

Or it is simply overengineering, as there should bot be so many release at all and maintaining this functionality is more effort than benefit.

**Comment by fhemberger** [comment]
+1 for `version.py`, as it's also a good reminder to bump the version in there as well.

I don't think we need an automated semantic release workflow at the moment.

**Comment by poggenpower** [comment]
Done. Version moved into version.py and imported into mqtt_exporter.py
