### ISSUE TITLE
Docker image v1.2.3 tagged as latest

### ISSUE THREAD

**Issue by ccoors** [fhemberger/mqtt_exporter#30]
The Docker image for v1.2.3 is marked as latest, which leads to most people not using the latest version v1.4.0. Maybe they were built in the wrong order. Can this be fixed?

![image](https://user-images.githubusercontent.com/8963459/137755467-d80e11e5-bd14-466e-9a6a-113f289230f3.png)

**Comment by ivan-alfonso** [comment]
If you use the tag ":latest" to download the image, you will get an older version (I had errors when using "enum" metrics). I solved it by using the tag ":v1.4.0". Thanks a lot for this work.

**Comment by fhemberger** [comment]
Sorry for leaving this unresolved for such a long time. I was hoping to have a new release by now that would fix the `latest` issue automatically. I will re-publish the Docker image for v1.4.0/commit 39daa01 as `latest` and `v1.4.0` in the next days. It's not recommended to re-publish existing tags but I don't see a better way to solve this right now.

**Comment by fhemberger** [comment]
Pushed `v1.4.0` and `latest` tags again to both Docker Hub and GitHub Container Registry. Sorry for the inconvenience.
