### ISSUE TITLE
no automatic image updates

### ISSUE THREAD

**Issue by poggenpower** [fhemberger/mqtt_exporter#39]
Hi,

it seems the action automatically publishing the updated images is broken. At least the images with the latest security patches 2 days ago doesn't got published. 

Bye
 Thomas

**Comment by fhemberger** [comment]
The pipeline only updates the image on new Git tags, not when pushing directly to master. The latest commits were mostly related to updates on GitHub actions, not sure the Python base image update warrants a new release.

At least according to the release notes, there are no security related updates:
https://www.python.org/downloads/release/python-3102/

**Comment by poggenpower** [comment]
Hi,

I think there are no security issues in python itself, but the base https://trivy.dev/results/?image=fhemberger/mqtt_exporter:latest especially the vulnerability in the xml lib could also impact python if linked against.

**Comment by fhemberger** [comment]
Updated to v1.4.1 with new base image, closing.
