### ISSUE TITLE
How can I convert strings to prometheus metrics?

### ISSUE THREAD

**Issue by mad-ady** [fhemberger/mqtt_exporter#4]
Hello!
Nice project!
I'd like to parse some telemetry data from my Tasmotized SonOffs to prometheus (and Grafana). I'm interested in getting their status (Online or Offline) and some details.
The status is exposed at `tele/<sensor>/LWT`. I think I need to create a label based on the value read and override the value. For instance set: 
```
my_sensor{topic="tele/<sensor>/LWT", state="Online"} 1
my_sensor{topic="tele/<sensor>/LWT", state="Offline"} 0
```
More details are exported as json at `tele/<sensor>/STATE`:
```
{
  "Time": "2021-02-17T14:48:23",
  "Uptime": "4T06:37:41",
  "Vcc": 3.427,
  "POWER": "OFF",
  "Wifi": {
    "AP": 1,
    "SSId": "MySSID",
    "RSSI": 52,
    "APMac": "AA:BB:CC:DD:EE:FF"
  }
}
```
This needs to be broken down like this:
```
my_sensor{topic="tele/<sensor>/STATE", POWER="Off"} 1
my_sensor{topic="tele/<sensor>/STATE", POWER="On"} 0
my_sensor{topic="tele/<sensor>/STATE", SSId="MySSID"} 1
my_sensor{topic="tele/<sensor>/STATE", RSSI=""} 52
```
Any idea if it's possible to do something like this with your code (via configuration only)?
Thanks!

**Comment by poggenpower** [comment]
At the moment this is not implemented https://github.com/fhemberger/mqtt_exporter/blob/master/mqtt_exporter.py#L269-L274 the value must be convertible into a float. The only conversion done is replacing the decimal delimiter `,` to a `.`(dot) for some European countries like Germany or France. 
I thought about adding some general mappings for ON, OFF, YES, NO, but before working on that I want to here from @fhemberger if he is open for PRs.

**Comment by fhemberger** [comment]
@poggenpower Thanks for your feedback, of course I'm open to PRs. I forked this repo myself to scratch my own itch (converting it to Python 3 and get my own sensor setup up and running), but I'm neither a Python nor MQTT expert. If you encounter any issues or if a basic feature seems to be missing, I'm glad for any help.

**Comment by poggenpower** [comment]
Not saying I am a python guru, but your code looks pretty good.
Back to the issue. 
I am thinking about to move the check far later in the process and e.g. defaulting to `0` instead of removing the metric.

Have not tried it out jet, but with the label replace you should already be able to replace __value__ with something else. Mean you can already can do something like:
` - source_labels:  ["__value__"]
        regex: "MySSID"
        target_label: "__value__"
        replacement: 1
        action: "replace"
`
There is another use case. Some senors publishing reading with units, e.g. 25,4ºC. A block like:
`  - source_labels:  ["__value__"]
        regex: "(.*)ºC"
        target_label: "location"
        replacement: '\1'
        action: "replace"
`
Could convert could parse out the number and make it working with prometheus. 

Purposed solution:
- remove the precheck https://github.com/fhemberger/mqtt_exporter/blob/master/mqtt_exporter.py#L269-L274 
- Add a check after label processing 
   - if a float, pass
   - if in 'ok', 'an', 'on', 'yes' (case insensitive) set to 1 
   - else set to 0 and log an info.

**Comment by poggenpower** [comment]
@mad-ady I think I found a solution and have implemented it. If you would like to test it, check out this Version https://github.com/poggenpower/mqtt_exporter/tree/ENUM. Feedback is welcome. 
As other changes I will merge them into the master here after further testing and feedback.

**Comment by mad-ady** [comment]
Thanks! I'll try to test it sometime next week and report back!

Cheers!

**Comment by poggenpower** [comment]
@mad-ady were you able to test?

**Comment by mad-ady** [comment]
@poggenpower sorry for not replying sooner. Been busy with school starting :)
I've just given it a try and it works! I have this sensor config:
```
# metric for a switch with the state on and off. 
# states are case sensitive and must match exactly
# use label_config to rewrite other values, see below.
metrics:
  - name: "kidslight_state"
    help: "Light state on/off"
    type: "enum"
    topic: "stat/kids_light/POWER"
    parameters:
      states: 
        - 'ON'
        - 'OFF'
```

These are the states that I get in prometheus:
```
kidslight_state{instance="mqtt_aldebaran", job="mqtt_aldebaran", kidslight_state="OFF", send_alerts="true", topic="stat/kids_light/POWER"} | 0
kidslight_state{instance="mqtt_aldebaran", job="mqtt_aldebaran", kidslight_state="ON", send_alerts="true", topic="stat/kids_light/POWER"} | 1
```

It seems to work just fine! Thanks for the change!
