### ISSUE TITLE
Feature Request: Docker Image for ARM64

### ISSUE THREAD

**Issue by roock** [fhemberger/mqtt_exporter#56]
I would like to use mqtt_exporter on an raspi and this would require arm64 container images. Would you be interested in providing such images and/or accepting PR?

**Comment by poggenpower** [comment]
Hi roock,

The Image should build fine on a Raspberry.
Clone the repo on a raspberry
cd into the repo and run
docker bulid -t mqtt-exporter .
docker Run mqtt-exporter

Bye Thomas

**Comment by fhemberger** [comment]
@roock Yes, I'd be interested in adding amd64 support and I'd gladly accept a PR (I always am).
As far as understand, a small adjustment to the GitHub action should be enough.

**Comment by fhemberger** [comment]
Added arm64 in the build pipeline, which will take effect with the next release.
I'm not really sure about increasing the version number when no changes in the code were made.

@roock Is this okay for you?

**Comment by poggenpower** [comment]
Technically there was a code change.- in the git action - , why not bumping the version tag by a minor.

**Comment by roock** [comment]
> Added arm64 in the build pipeline, which will take effect with the next release. I'm not really sure about increasing the version number when no changes in the code were made.
> 
> @roock Is this okay for you?

Totally fine for me. I didn't have time to start my shelly-mqtt project yet. Thank you for the fast response 👍
